#!/usr/bin/env bash
# This Prints the subdomains info

subdomain_info () {
    RT=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | awk '{print $4}' | tail -n 1)
    DEST=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | awk '{print $5}' | tail -n 1)
    echo "The subdomain $2 is a $RT record and points to $DEST"
}

if [ $# -eq 1 ]
then
    subdomain_info $1 "www"
    subdomain_info $1 "lb-01"
    subdomain_info $1 "web-01"
    subdomain_info $1 "web-02"
elif [ $# -gt 1 ]
then
    subdomain_info $1 $2
fi
