#!/usr/bin/env bash
#nginx server configured and redirected to another page
sudo apt-get -y update
sudo apt-get install -y nginx

sudo sed -i '/^\s*server_name \_\;$/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
