#!/usr/bin/env bash
# A script that installs and configure HAproxy on lb-01 server
sudo apt -y update
sudo apt -y upgrade
apt install -y haproxy;
echo "frontend http
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 64854-web-01	34.239.255.113:80 check
    server 64854-web-02	52.23.178.93:80 check" >> /etc/haproxy/haproxy.cfg
    service haproxy restart
