#!/usr/bin/env bash
#A bash script that configures nginx for listening to port 80

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
