#!/usr/bin/env bash
# Here is what this scripts does
# It Creates a file /var/run/myscript.pid containing its PID
# It Displays 'To infinity and beyond' indefinitely
# And then Displays 'I hate the kill command' when receiving a SIGTERM signal
# Displays 'Y U no love me?!' when receiving a SIGINT signal
# Finally, it Deletes the file /var/run/myscript.pid and terminates 
# itself when receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
