#!/usr/bin/env bash
# Here is what this script does
# It displays "To infinity and beyond indefinitely"
# And then With a "sleep 2" in between each iteration
# Displays "I am invincible!!!" when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
