#!/usr/bin/env bash
# Here is what this script does
# It displays the content of the file /etc/passwd.
# By only displaying the "username" "user id" and
# "Home directory path for the user"

while read -r line
do
	echo "$line"
done < /etc/passwd
