#!/usr/bin/env bash
# Here is what this script does
# It displays the content of the file /etc/passwd, using the while loop + IFS.
# Usage: IFS and while loop

while IFS=: read -r username password uid gid info home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "$info's place is protected by the passcode $password, more info about the user here: $uid"
done < /etc/passwd
