#!/usr/bin/env bash
# This is a script that displays Best School 10 times after which it displays 
# Best School and then Hi on the 9th iteration on a new line

count=0
while ((count <= 10))
do
	if ((count == 9))
	   then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
