#!/usr/bin/env bash
# This is a script that displays Best School 10 times after which it displays 
# Best School and then Hi on the 9th iteration on a new line

count=0
while [ "$count" -lt 10 ]; do
	echo "Best School"
	if [ "$count" -eq 8 ]
	then
	    echo "Hi"
	fi
	let count=count+1
done
