#!/usr/bin/env bash
# Here's what this script does
# loops from 1 to 10 and displays
# displays "bad luck" for the 4th loop iteration
# And then "good luck" for the 8th loop iteration
# And for other iterations, it displays "Best School"

count=1
while [ "$count" -le 10 ]; do
    if [ $count -eq 4 ]; then
	echo "bad luck"
    elif [ $count -eq 8 ]; then
	echo "good luck"
    else
	echo "Best School"
    fi
    let count++
done
