#!/usr/bin/env bash
# Here is what this cript does
# It displays numbers from 1 to 20
# It then displays "4" and then "bad luck from China" for the 
# 4th loop iteration
# It then displays "9" and then "bad luck from Japan" for the 
# 9th loop iteration
# It then displays "17" and then "bad luck from Italy" for the
# 17th loop iteration

count="1"
while [ "$count" -lt 21 ];do
	echo "$count"
	case $count in 
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((count++))
done
