#!/usr/bin/env bash
# Here is what this script does
# It gives information about the school file
# It checks if the files exists and prints "school file exists"
# It prints "school files does not exist" if it doesn't
# If it is a regular file, it prints "School is a regular file"
# If the file is not a regular file it prints nothing

school_file="school"
if [ -e "$school_file" ]; then
	echo "school file exists"
	if [ -s "$school_file" ]; then
		echo "school file is not empty"
		if [ -f "$school_file" ]; then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
		if [ -f "$school_file" ]; then
                        echo "school is a regular file"
                fi
	fi
else
	echo "school file does not exist"
fi
