#!/usr/bin/env bash
# This is what this bash script does
# It resolves localhost to 127.0.0.2
# It resolves facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i -e 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo  "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
